version: '3.9'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: jobtracker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://app:app@db:5432/jobtracker?schema=public
      JWT_SECRET: changeme
      PORT: 4000
      NODE_ENV: development
      STORAGE_PROVIDER: local
      UPLOAD_DIR: /app/uploads
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_SECURE: "false"
      SMTP_USER: ""
      SMTP_PASS: ""
      FROM_EMAIL: noreply@example.com
      OPENAI_API_KEY: ""
      RUN_MIGRATIONS_ON_START: "true"
    depends_on:
      - db
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - backend_uploads:/app/uploads

  frontend:
    build: ./frontend
    environment:
      VITE_API_BASE_URL: http://localhost:4000
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  pgdata:
  backend_uploads:

